// This file is generated by Velite

import type __vc from '../velite.config.mjs'

type Collections = typeof __vc.collections

export type Guide = Collections['guides']['schema']['_output']
export declare const guides: Guide[]
